### PR TITLE
include journal.go and LICENSE files in go-systemd, delete unused paths

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar lsm5@fedoraproject.org

@jwhonce This commit adds journal.go and its LICENSE, also removes unused paths in vendor/.

PTAL

### CODE REVIEW

**Comment by rhatdan** [comment]
Why apache license?  I prefer GPLV2+ or GPLV3

**Comment by lsm5** [comment]
ohh hmm, I just included go-systemd's original LICENSE in there, is it ok to change to GPL\* ?

**Comment by rhatdan** [comment]
I don't see why not.

**Comment by lsm5** [comment]
cool, I could simply delete the LICENSE file from in there which should imply the main LICENSE applies in vendor as well. wdyt?

**Comment by rhatdan** [comment]
Sure

**Comment by lsm5** [comment]
updated, also recorded upstream commit value used.

**Comment by lsm5** [comment]
@rhatdan ping, could you please merge this if it LGTY? I need this to update our rhel rpms.

**Comment by rhatdan** [comment]
@lsm5 I think I just gave you bad info, I thought this was our code.  Not coreos, code.  We can not change their license.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
